Added a method to stop the count down

diff --git a/pss b/pss
--- a/pss
+++ b/pss
@@ -4,48 +4,84 @@
 
 # Change this uri to play yours spotify playlist
 URI="spotify:user:yeray007n2:playlist:1OblHqckaTmCmvVVGCTE4J"
+# Change this if you saved the script with a different name
+COMMAND_NAME="pss"
+
+# CONSTANTS
 
 SP_DEST="org.mpris.MediaPlayer2.spotify"
 SP_PATH="/org/mpris/MediaPlayer2"
 SP_MEMB="org.mpris.MediaPlayer2.Player"
+
 HELP_COMMAND_1="-h"
 HELP_COMMAND_2="--help"
+STOP_COMMAND="stop"
 SPOTIFY_SLEEP=2
-function dbus {
+
+# SHELL OPTIONS
+
+shopt -s expand_aliases
+
+# UTILITY FUNCTIONS
+
+function require {
+  hash $1 2>/dev/null || {
+    echo >&2 "Error: '$1' is required, but was not found."; exit 1;
+  }
+}
+
+# COMMON REQUIRED BINARIES
+
+# We need dbus-send to talk to Spotify.
+require dbus-send
+
+# Assert standard Unix utilities are available.
+require grep
+require echo
+require sleep
+require pkill
+require shutdown
+
+function pss-dbus {
   # Sends the given method to Spotify over dbus.
   dbus-send --print-reply --dest=$SP_DEST $SP_PATH $SP_MEMB.$1 ${*:2} > /dev/null
 }
 
-function open {
+function pss-open {
   # Opens the given spotify: URI in Spotify.
-  dbus OpenUri string:$1
+  pss-dbus OpenUri string:$1
 }
 
-function print_help {
+function pss-print_help {
 	echo "Usage: pss [time]"
 	echo "Shutdown your pc after X minutes and play a playlist during 10 minutes (default)."
 	echo ""
 	echo "  pss 5       - Music starts to play after 5 minutes and your pc is shutdown after 10 minutes (default)"
 	echo "  pss 5 8     - Music starts to play after 5 minutes and your pc is shutdown after 8 minutes"
 }
-function isvalidparameter {
+function pss-isvalidparameter {
 	if [[ -z "$1" ]]; then
 		return 1
 	else
 		return 0
 	fi
 }
-function isinteger {
+function pss-isinteger {
 	if [ "$1" -eq "$1" ] 2>/dev/null; then
 		return 0
 	else
 		return 1
 	fi
 }
-function error {
+function pss-error {
 	echo $1
 	echo $USAGE
 	exit 1
+}
+function pss-stop {
+	pss-dbus "Pause" > /dev/null
+	pkill -f $COMMAND_NAME
+	shutdown -c
 }
 
 
@@ -54,14 +90,14 @@ function error {
 time=$1
 shutdowntime=$2
 
-if isvalidparameter $time; then
+if pss-isvalidparameter $time; then
 	# if [ "$time" -eq "$time" ] 2>/dev/null
-	if isinteger $time;
+	if pss-isinteger $time;
 	then
 		# Getting shutdown time
-		if isvalidparameter $shutdowntime; then
-			if ! isinteger $shutdowntime; then
-				error "ERROR: shutdown time must be an integer."
+		if pss-isvalidparameter $shutdowntime; then
+			if ! pss-isinteger $shutdowntime; then
+				pss-error "ERROR: shutdown time must be an integer."
 			fi
 		else
 			shutdowntime=10
@@ -78,16 +114,17 @@ if isvalidparameter $time; then
 		  spotify & sleep $SPOTIFY_SLEEP
 		fi
 			# Playing list
-		open $URI
+		pss-open $URI
 	else
-shopt -s nocasematch
-
-		if [ "${time,,}" == "$HELP_COMMAND_1" ] || [ "${time,,}" == "$HELP_COMMAND_2" ] ; then
-			print_help
-		else
-			error "ERROR: sleep time must be an integer."
-		fi
+		  # Arguments given, check if it's a command.
+		 if [ "${time,,}" == "$HELP_COMMAND_1" ] || [ "${time,,}" == "$HELP_COMMAND_2" ] ; then
+		 	pss-print_help
+		 elif [ "${time,,}" == "$STOP_COMMAND" ]; then
+			pss-stop
+		 else
+		 	pss-error "ERROR: sleep time must be an integer."
+		 fi
 	fi
 else
-	print_help
+	pss-print_help
 fi
